### PR TITLE
Handle Fireworq's "claimed" status.

### LINKED ISSUE #53: Fireworq's "claimed" status is incorrectly handled.
"claimed" --> "in-progress"

### PR DESCRIPTION
**Pull request by Foxcapades**
Resolves #53

### CODE REVIEW

File: rest-service/queue/src/main/java/mb/lib/extern/model/JobStatusResponse.java [hunk 1]
```diff
@@ -7,16 +7,16 @@
 @JsonIgnoreProperties(ignoreUnknown = true)
 public class JobStatusResponse
 {
-  private String status;
+  private QueueJobStatus status;
```
Comment (Foxcapades) [inline rest-service/queue/src/main/java/mb/lib/extern/model/JobStatusResponse.java:10]: Converted the internal type because I was a fool before for not storing it this way.

**Review by jtlong3rd — APPROVED** [review]
